import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import MerchModal from '@/components/MerchModal';
import { LoadingProvider } from '@/contexts/LoadingContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ieee_ruhuna_IAS",
  description: "Generated by create next app",
  icons: {
    icon: "./images/IEEE-UoR-Logohalf.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingProvider>
          <MerchModal />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}